name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Build Web
        run: |
          flutter pub get
          flutter build web --release --wasm --web-resources-cdn
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
      - name: Get time in seconds
        id: seconds
        run: echo "seconds=$(date +'%s')" >> $GITHUB_OUTPUT
